### ISSUE TITLE
Nifi throws an exception on startup.

### ISSUE THREAD

**Issue by n2mp60** [olegz/nifi-ide-integration#2]
Followed the instructions in the README.md file.  Nifi won't start as there's no properties file found.  NifiProperties.java expects the system property, PROPERTIES_FILE_PATH, to be set on startup.  So two problems here - 1. System property is not set, but README.md could be updated to include this as a necessary setting in the Eclipse Run configuration, and 2. nifi.properties file needs to be generated as part of the Eclipse project files.  
One other aside, there isn't a log4j properties file so you don't see the error message thrown.

**Comment by olegz** [comment]
Yes, that is correct. I need to update the docs. There is a missing step where when you configure runnable you also have to provide -D for nifi.properties.
Also, keep in mind that you need to update to the latest version in build.gradle (e.g., 1.0.0-snapshot)

I'll find time to polish the docs

**Comment by cupdike** [comment]
I've got the -D-Dnifi.properties.file.path included but I get:

```17:00:24,947  INFO main nifi.NiFi:225 - Launching NiFi...
17:00:24,956  INFO main nifi.NiFi:88 - NiFi started without Bootstrap Port information provided; will not listen for requests from Bootstrap
17:00:24,970 ERROR main nifi.NiFi:229 - Failure to launch NiFi due to java.lang.IllegalStateException: Unable to find the framework NAR ClassLoader.
java.lang.IllegalStateException: Unable to find the framework NAR ClassLoader.
	at org.apache.nifi.NiFi.<init>(NiFi.java:116)
	at org.apache.nifi.NiFi.main(NiFi.java:227)
17:00:24,972  INFO Thread-0 nifi.NiFi:152 - Initiating shutdown of Jetty web server...
17:00:24,972  INFO Thread-0 nifi.NiFi:159 - Jetty web server shutdown completed (nicely or otherwise).
```

And I see nifi-nar-utils jar in the referenced libraries.  Any idea what's wrong?

**Comment by pizhihui** [comment]
@cupdike I've got the same problem,  Do we need change the nifi-runtime jar's version?
