### ISSUE TITLE
Nifi throws an exception on startup

### ISSUE THREAD

**Issue by mafujian** [olegz/nifi-ide-integration#3]
Failure to launch NiFi due to java.lang.RuntimeException: Requires a system property called 'nifi.properties.file.path' and this is not set or has no value
java.lang.RuntimeException: Requires a system property called 'nifi.properties.file.path' and this is not set or has no value
	at org.apache.nifi.util.NiFiProperties.getInstance(NiFiProperties.java:255)
	at org.apache.nifi.NiFi.main(NiFi.java:227)

**Comment by yuri1969** [comment]
This sounds like the `nifi.properties.file.path` should point to NiFi's `conf/nifi.properties` file.
