### ISSUE TITLE
Provider org.apache.nifi.kerberos.KerberosProvider could not be instantiated

### ISSUE THREAD

**Issue by saurabhbidwai** [olegz/nifi-ide-integration#5]
15:31:47,943  INFO main nifi.NiFi:225 - Launching NiFi...
15:31:47,980  INFO main nifi.NiFi:88 - NiFi started without Bootstrap Port information provided; will not listen for requests from Bootstrap
15:33:00,716 ERROR main nifi.NiFi:229 - Failure to launch NiFi due to java.util.ServiceConfigurationError: org.apache.nifi.authentication.LoginIdentityProvider: Provider org.apache.nifi.kerberos.KerberosProvider could not be instantiated
java.util.ServiceConfigurationError: org.apache.nifi.authentication.LoginIdentityProvider: Provider org.apache.nifi.kerberos.KerberosProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.nifi.nar.ExtensionManager.loadExtensions(ExtensionManager.java:107)
	at org.apache.nifi.nar.ExtensionManager.discoverExtensions(ExtensionManager.java:88)
	at org.apache.nifi.NiFi.<init>(NiFi.java:120)
	at org.apache.nifi.NiFi.main(NiFi.java:227)
Caused by: java.lang.NoClassDefFoundError: org/apache/nifi/authentication/exception/ProviderCreationException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.nifi.authentication.exception.ProviderCreationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
15:33:00,725  INFO Thread-0 nifi.NiFi:152 - Initiating shutdown of Jetty web server...
15:33:00,725  INFO Thread-0 nifi.NiFi:159 - Jetty web server shutdown completed (nicely or otherwise).

**Comment by saurabhbidwai** [comment]
Upgraded the Gradle dependency to version 1.4.0

dependencies {
    compile "org.apache.nifi:nifi-api:1.4.0" 
    compile "org.apache.nifi:nifi-runtime:1.4.0"  
    compile "org.apache.logging.log4j:log4j-core:2.4"
    compile "org.slf4j:slf4j-api:1.7.12"
    compile "org.slf4j:slf4j-log4j12:1.7.12"
    compile "org.slf4j:jul-to-slf4j:1.7.12"
	runtime "javax.servlet:javax.servlet-api:3.1.0"  
}
